### PR TITLE
Fix #44 so events are no longer backwards in tests.

### LINKED ISSUE #44: Fix the backwards events tests
Stumbled into this when working on #39 - our event observer actually fires backwards (and our tests catch things in reverse order) because the event priority is wrong.  Kinda.

### PR DESCRIPTION
**Pull request by caffodian**
When working on making things async, the events no longer always directly call each other.

This exposed a bug where because the test helper used to listen for event names had the wrong priority, we were actually listening to things backwards in order to compensate for this.

The correct thing is to have the events in correct order, and fix the priority of the test event listeners so they more accurately reflect reality.

(For example:  event A's handler calls event B (all synchronous) which calls event C - if the priorities are such that the plugin code catches the event before the test, you can actually get the events in C, B, A order in the test code.  Once this becomes more complex + some of the events are async, it becomes crazy if it's inconsistent.)

### CODE REVIEW

**Comment by caffodian** [comment]
Surprisingly didn't break too many things by doing this.

File: tests/smoke/events.js [hunk 1]
```diff
@@ -49,7 +49,7 @@
 			bot.setHtmlWithSelection(starterHtml);
 
 			resumeAfter(editor, 'spellCheckComplete', function () {
-				observer.assert(["spellCheckComplete", "startRender", "startCheckWordsAjax", "startScanWords"])
+				observer.assert(["startScanWords", "startCheckWordsAjax", "startRender", "spellCheckComplete"])
```
Comment (winhamwr) [inline tests/smoke/events.js:52]: This order makes much more sense :)

File: tests/smoke/events.js [hunk 2]
```diff
@@ -195,12 +195,12 @@
 			observer.events.push(evt);
 		}
 
-		editor.on('startSpellCheckOn', stdObserver);
-		editor.on('startScanWords', stdObserver);
-		editor.on('startCheckWordsAjax', stdObserver);
-		editor.on('startRender', stdObserver);
-		editor.on('spellCheckComplete', stdObserver);
-		editor.on('spellCheckAbort', stdObserver);
+		editor.on('startSpellCheckOn', stdObserver, null, null, -999);
```
Comment (winhamwr) [inline tests/smoke/events.js:198]: What are those last 3 arguments doing?

**Review by winhamwr — APPROVED** [review]
:+1:

File: tests/smoke/events.js (hunk 2 above)
Comment (caffodian) [reply tests/smoke/events.js:198]: One is a value for `this`, the other is listenerData (kind of like standard params that are passed only into this listener for this event), and then the -999 is priority (very high) 

http://docs.ckeditor.com/#!/api/CKEDITOR.event-method-on

File: tests/smoke/events.js (hunk 1 above)
Comment (caffodian) [reply tests/smoke/events.js:52]: it gets a bit weird in the next one because some of them are more async than others.  but we'll get there soon...
