### PR TITLE
fix #39 - don't use a mutation-insensitve bookmark when performing mutations

### LINKED ISSUE #39: Quick fix: can't actually use bookmarks2 for marking words
Our word scanning will switch immediately to marking if all words already exist in cache.  It attempts to use bookmarks2 for this as well, which is wrong, because bookmarks2 is not mutation sensitive.  Sigh.

### PR DESCRIPTION
**Pull request by caffodian**
It has some...problems with the current approach.  This is a quick fix, that won't take too much thought, until I wrangle all the other bookmarking issues in #38 

This also fixes the problem where multiple selection bookmarks are created in the shortcut case.

### CODE REVIEW

**Comment by caffodian** [comment]
Although this normally shouldn't matter, there seems to be a strange interaction between:
- "ignore a word if it has a bookmark in it + skip to the next word" + non-normalized text nodes
- whatever craziness happens when the span gets removed, resulting in non-normalized text nodes

**Comment by caffodian** [comment]
Also, more importantly, marking doesn't actually work if you try to use a mutation insensitive bookmark.  Which I knew, but I missed the short circuit case.

**Comment by caffodian** [comment]
..we can't refactor it because it makes the check vs. render decision on a block to block basis, as well.  will get better when we refactor things out.

**Comment by caffodian** [comment]
summary of my rambling, so that I remember why I can't test this easily:

This is actually an interaction of a few things:
- there are no new words, because scanning works correctly with bookmarks2
- bookmarks 2 is incorrectly being used for marking, if there are no new words
- selection goes crazy because the rest of the block gets marked with an selection insensitive bookmark

**Comment by caffodian** [comment]
how this could be tested better:  pass the output of getHtmlWithSelection into spellcheck cases, hopefully it doesn't get broken by testcase html normalization.

**Comment by caffodian** [comment]
Argh.  Because `getData()` cleans the html of spellcheck spans, it is not possible to assert where the spans are + ensure selection is stable in the same call.

**Comment by caffodian** [comment]
I am glad I persisted in trying to get it tested, because there is actually a related bug related to having two bookmarks beside each other.  :/

File: plugins/nanospell/plugin.js [hunk 1]
```diff
@@ -803,8 +803,7 @@
 				var combinedText = '',
 					block,
 					blockList = [],
-					iterator = range.createIterator(),
-					bookmarks = editor.getSelection().createBookmarks2(false);
```
Comment (caffodian) [inline plugins/nanospell/plugin.js:807]: it was possible to then enter a shortcut case where we immediately start marking words.  also, because of things-yet-to-be-refactored (improve detection of whether a bookmark is actually needed + `setTimeout(render,0)` ), the shortcut case would then create a second bookmark immediately beside the invisible one, which in itself is a mutation.  

so making the decision to create a mutation insensitive is now made inside the actual getWords function below.  Since it is a mutation insensitive bookmark and doesn't need to be restored, it is worse than not creating a bookmark at all, but not nearly as bad as creating/restoring a mutation sensitive bookmark for each block.

File: plugins/nanospell/plugin.js [hunk 2]
```diff
@@ -819,12 +818,13 @@
...
 					startCheckOrMarkWords(getUnknownWords(combinedText), blockList);
 				}
-				editor.getSelection().selectBookmarks(bookmarks); // we may not need to select, just blow it up
+
 			}
 
 			function getWords(block) {
 				var range = editor.createRange(),
 					currentWordObj,
+					bookmarks = editor.getSelection().createBookmarks2(false),
```
Comment (caffodian) [inline plugins/nanospell/plugin.js:839]: bookmarks2 is a mutation insensitive bookmark (no span is created) therefore we can create it when scanning for words in order for the "don't check this current word" logic to work, without  restoring the selection to the bookmark afterwards.

File: tests/spellchecking/spellcheck.js [hunk 3]
```diff
@@ -56,14 +58,38 @@
 				tc = this,
 				editor = bot.editor,
 				resumeAfter = bender.tools.resumeAfter,
-				starterHtml = '<p>Paragraph with missspelling</p>';
+				// phantom (on travis) sometimes does weird things around caret + trailing spaces
+				// so putting a word that is skipped is easier
+				starterHtml = '<p>Paragraph with missspelling skipme^</p>';
```
Comment (caffodian) [inline tests/spellchecking/spellcheck.js:63]: weird.

File: tests/spellchecking/spellcheck.js [hunk 4]
```diff
@@ -56,14 +58,38 @@
...
 			resumeAfter(editor, 'spellCheckComplete', function () {
 				var paragraph = editor.editable().findOne('p');
 
-				tc.assertHtml('<p>Paragraph with <span class="nanospell-typo">missspelling</span></p>', paragraph.getOuterHtml());
+				tc.assertHtml('<p>Paragraph with <span class="nanospell-typo">missspelling</span> skipme</p>', paragraph.getOuterHtml());
+			});
+
+			wait();
+		},
+		'test cursor stability when words are skipped in spellcheck': function () {
```
Comment (caffodian) [inline tests/spellchecking/spellcheck.js:75]: may be redundant, the modified test probably handles this better.  but it's easier to see where something is wrong with this simpler input.

File: tests/spellchecking/spellcheck.js [hunk 5]
```diff
@@ -73,14 +99,18 @@
...
 				resumeAfter = bender.tools.resumeAfter,
-				starterHtml = '<p>Paragraph with mis<b>s</b>s<i>pe</i>lling</p>';
+				starterHtml = '<p>Paragraph with mis<strong>s</strong>s<em>pe</em>lling skipme^</p>',
+				htmlWithSelection;
 
 			bot.setHtmlWithSelection(starterHtml);
 
 			resumeAfter(editor, 'spellCheckComplete', function () {
 				var paragraph = editor.editable().findOne('p');
+				htmlWithSelection = bender.tools.getHtmlWithSelection(editor);
```
Comment (caffodian) [inline tests/spellchecking/spellcheck.js:109]: Interesting fact - the b -> strong and i -> em conversions only happen because we call this helper function, which then indirectly triggers filters.

File: plugins/nanospell/plugin.js (hunk 2 above)
Comment (winhamwr) [reply plugins/nanospell/plugin.js:839]: Do you think it's worth explaining the "why" of this in a comment, here? I found this explanation very useful.

**Review by winhamwr — APPROVED** [review]
Looks good! Hooray for fewer selection manipulations.

**Comment by caffodian** [comment]
> Looks good! Hooray for fewer selection manipulations.

technically this is more (vs. the previous version, but not the version before that.)  This does fix the nasty gross bugs around double-bookmarking that i accidentally caused in the previous version, though, while keeping most of the performance benefits

**Comment by caffodian** [comment]
Ugh. There is a weird undo bug around adding more to a typo, waiting for spellcheck, and then undoing it

**Comment by winhamwr** [comment]
> technically this is more

Hrm. Maybe I'm misunderstanding, then. I thought you're now storing a bookmark to the current selection more often, but no longer manipulating the selection (e.g. modifying the current selection to match the selection that was stored in the bookmark).

**Comment by caffodian** [comment]
> Hrm. Maybe I'm misunderstanding, then. I thought you're now storing a bookmark to the current selection more often, but no longer manipulating the selection (e.g. modifying the current selection to match the selection that was stored in the bookmark).

Oh, yea.  From that perspective, there is less selection manipulation.  I sometimes mix up "bookmark derived from selection" & selection itself

**Comment by caffodian** [comment]
I feel like there are still some things we are doing wrong, but they can be more easily improved when we also stop doing bookmarks when not needed. ( #38 )
