### PR TITLE
Ie11 selection fun (fixes #33)

### LINKED ISSUE #33: Selection is not stable in IE11 (probably due to bookmarks)
Creating a bookmark in IE11 modifies the selection ranges.

In the `render` method, before going in and marking spans, we create a bookmark at the current selection.  This causes the really simple "ignore the current selection" code in the Wordwalker to fail.  

There are a few ways out of this:

1)  Really optimistically:  because we no longer care about marking the current word, we no longer need to set bookmarks in order for the cursor to not move (very unlikely this actually works, but worth trying)
2)  get the selection before creating the bookmark, since we only care about it for the purposes of marking the text node that we don't care about. this may still not work since the bookmark might do something bad.  
3)  take another pass at the "find the currently selected word" code.  It should also ignore empty trailing children instead of just always looking at the last child.  (I am most sure that this will work, though it feels the most hacky)

### PR DESCRIPTION
**Pull request by caffodian**
Fixes #33 by creating new word walkers after hitting a bookmark, which start walking from the next word after the bookmark.

### CODE REVIEW

File: plugins/nanospell/plugin.js [hunk 1]
```diff
@@ -87,7 +105,6 @@
 			var condition = node.type == CKEDITOR.NODE_TEXT && // it is a text node
 				node.getLength() > 0 &&  // and it's not empty
 				( !node.isReadOnly() ) &&   // or read only
-				isNotBookmark(node) && // and isn't a fake bookmarking node
```
Comment (caffodian) [inline plugins/nanospell/plugin.js:90]: We used to walk over bookmarks but ignore them.  Now we actually stop.

File: plugins/nanospell/plugin.js [hunk 2]
```diff
@@ -108,8 +124,8 @@
 			return condition;
 		}
 
-		ww.rootBlockTextNodeWalker = new CKEDITOR.dom.walker(range);
-		ww.rootBlockTextNodeWalker.evaluator = isRootBlockTextNode;
```
Comment (caffodian) [inline plugins/nanospell/plugin.js:112]: init code moved into method

File: plugins/nanospell/plugin.js [hunk 3]
```diff
@@ -141,79 +161,67 @@
...
-			// sometimes you can have a selection
-			// which has no ranges...?!
-			if (ranges.length === 0) {
-				return null;
-			}
-
-			selectionRange = selection.getRanges()[0];
-			selectionNode = selectionRange.startContainer;
-			selectionOffset = selectionRange.startOffset;
-			selectionChildren = selectionNode.getChildren ? selectionNode.getChildren() : null;
```
Comment (caffodian) [inline plugins/nanospell/plugin.js:164]: Removed the bad previous approach

File: plugins/nanospell/plugin.js [hunk 4]
```diff
@@ -141,79 +161,67 @@
...
-				}
-				else if (selectionOffset >= selectionChildren.count()) {
-					// selection is past the end element, attempt to move into its last child, at the end
-					selectionRange.moveToPosition(selectionChildren.getItem(selectionChildren.count()-1), CKEDITOR.POSITION_BEFORE_END)
-				}
-				else {
-					// selection is somewhere in between children of the container
-					// move into the child that follows the selection and place the cursor at the start
-					selectionRange.moveToPosition(selectionChildren.getItem(selectionOffset), CKEDITOR.POSITION_AFTER_START)
-				}
```
Comment (caffodian) [inline plugins/nanospell/plugin.js:184]: more removal

File: plugins/nanospell/plugin.js [hunk 5]
```diff
@@ -141,79 +161,67 @@
...
+			return i;
 
-				if (selectionNode.equals(selectionRange.startContainer) && selectionOffset === selectionRange.startOffset) {
-					// We hit a crazy case (usually breaks or other non-text containing elements in between)
-					// where the selection doesn't actually move.
-					// We are unable to traverse any further, so abort.
-					return null;
-				}
+		},
+		initializeNodeWalker: function(lastRangeFound) {
```
Comment (caffodian) [inline plugins/nanospell/plugin.js:178]: new function to init the walker (this diff went crazy.)

File: plugins/nanospell/plugin.js [hunk 6]
```diff
@@ -141,79 +161,67 @@
...
-			}
-			else {
-				// we somehow managed to exhaust all possible nodes without finding a text node
-				return null;
 			}
 		},
+		normalizeWord: function (word) {
+			// hex 200b = 8203 = zerowidth space
+			return word.replace(/\u200B/g, '');
+		},
```
Comment (caffodian) [inline plugins/nanospell/plugin.js:224]: not actually new, crazy diff thinks it was moved.

File: plugins/nanospell/plugin.js [hunk 7]
```diff
@@ -226,18 +234,6 @@
...
-			var isSelectedWord = false;
-
-
-			if (selection) {
-				var selectionMarker = ww.getTextNodePositionFromSelection(selection);
-				if (selectionMarker) {
-					selectionNode = selectionMarker.node;
-					selectionOffset = selectionMarker.offset;
-				}
-			}
```
Comment (caffodian) [inline plugins/nanospell/plugin.js:240]: leftover non-working IE11 approach

File: plugins/nanospell/plugin.js [hunk 8]
```diff
@@ -268,21 +264,9 @@
...
-					else if (currentTextNode.equals(selectionNode) && selectionOffset === i) {
-						isSelectedWord = true;
-					}
-				}
-				// catch case where the caret was touching the back of the text node
-				// normally this should only be at the very end of the block
-				// since we prefer to put the caret at the start of text nodes
-				// but things can be weird.
-				if (currentTextNode.equals(selectionNode) && selectionOffset === i) {
-					isSelectedWord = true;
```
Comment (caffodian) [inline plugins/nanospell/plugin.js:285]: all this is just removing cruft from the broken approach

File: tests/spellchecking/spellcheck.js [hunk 9]
```diff
@@ -600,7 +600,7 @@
 				resumeAfter = bender.tools.resumeAfter;
 
 			bot.setHtmlWithSelection(
-				'<p><span class="nanospell-typo">qui</span>^<span class="nanospell-typo">asdf</span></p>'
+				'<p><span class="nanospell-typo">qui</span><span class="nanospell-typo">asdf</span> ^</p>'
```
Comment (caffodian) [inline tests/spellchecking/spellcheck.js:603]: Unrelated test that was failing because the "ignore word that the caret is on" now works properly for this case.  so just moved the caret out.

File: tests/typowalking/wordwalker.js [hunk 10]
```diff
@@ -5,7 +5,10 @@
 
 bender.editor = {
 	config: {
-		enterMode: CKEDITOR.ENTER_P
+		enterMode: CKEDITOR.ENTER_P,
+		nanospell: {
+			autostart: false
+		}
```
Comment (caffodian) [inline tests/typowalking/wordwalker.js:11]: otherwise, multiple walkers run at the same time, and can screw up the bookmark.

File: tests/typowalking/wordwalker.js [hunk 11]
```diff
@@ -291,7 +300,7 @@ bender.test( {
 			wordsReturned;
 
 		bot.setHtmlWithSelection(
-			"<p>couldn't shouldn't wouldn't dunno'grammar ^</p>"
+			"<p>couldn't shouldn't wouldn't dunno'grammar</p>"
```
Comment (caffodian) [inline tests/typowalking/wordwalker.js:303]: no selection is required

File: plugins/nanospell/plugin.js [hunk 12]
```diff
@@ -59,11 +59,29 @@
 		// (for example, p, li, td)
 		// and provides a mechanism for iterating over each word within,
 		// ignoring non-block elements.  (for example, span)
-		var isNotBookmark = CKEDITOR.dom.walker.bookmark(false, true);
+		var bookmarkGuardFn = CKEDITOR.dom.walker.bookmark(false, true);
```
Comment (caffodian) [inline plugins/nanospell/plugin.js:62]: In a CKEDITOR dom walker, the "guard" function (it's an actual parameter) is a function that is called on every node to figure out if you should abort the walk.  

We wrap this function below in order to actually store the result, and I couldn't think of a good name for the original.  :/

Comment (caffodian) [reply plugins/nanospell/plugin.js:62]: ^ Not the result, but the node that failed.

Comment (caffodian) [reply plugins/nanospell/plugin.js:62]: Hm, you deleted your comment and made me look like a crazy person.  I'll remember this :p

Comment (bocribbz) [reply plugins/nanospell/plugin.js:62]: haha sorry, it kind of made sense later on...

Comment (bocribbz) [reply plugins/nanospell/plugin.js:62]: Initial question was: 

> why `GuardFn`?

Comment (caffodian) [reply plugins/nanospell/plugin.js:62]: BTW, I don't know if you are aware, but http://docs.ckeditor.com/ can be used to search for any of the "CKEDITOR.*" concepts/functions, if you are curious about things (like what the dom walker actually is )

**Comment by bocribbz** [comment]
looks good.
